version: "3.7"
services:
  smart-lock-sql-server:
    container_name: "smart-lock-sql-server"
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1337:1433"
    environment:
      SA_PASSWORD: "Str0ng!Pass"
      ACCEPT_EULA: "Y"
  smart-lock-frontend-app:
    container_name: "smart-lock-frontend-app"
    build: ../dockerfile
    ports:
      - "6969:80"