version: "3.7"
services:
  smart-lock-sql-server:
    container_name: "smart-lock-sql-server"
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1337:1433"
    environment:
      SA_PASSWORD: "Str0ng!Pass"
      ACCEPT_EULA: "Y"
  smart-lock-frontend-app:
    container_name: "smart-lock-frontend-app"
    build: .
    ports:
      - "4200:4200"
    volumes:
      - ../Solution/Application/Frontend/SmartLock:/data
      - ./Scripts:/scripts
    command: sh -c "./scripts/Script.sh"